# Generated by Django 2.2.2 on 2019-06-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title'], 'verbose_name': 'Blog'},
        ),
    ]
